title = "Claus' Blog"
baseURL = "https://blog.cmmx.de"
theme = "hugo-cloonix"
timeZone = "Europe/Berlin"
copyright = "2024 Claus Malter"
languageCode = "en-us"

enableEmoji = true
enableRobotsTXT = true
summaryLength = 40

# Setup syntax highlighting without inline styles. For more information about
# why you'd want to avoid inline styles, see
# https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/style-src#unsafe_inline_styles
[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 2
    ordered = false
  [markup.highlight]
    lineNos = false
    lineNumbersInTable = false
    # This allows Bear Cub to use a variation of Dracula that is more accessible
    # to people with poor eyesight. For more information about color contrast
    # and accessibility, see https://web.dev/color-and-contrast-accessibility/
    noClasses = false

[params]
  description = "Blog based on Hugo SSG and Github pages"
  favicon = "images/favicon.png"
  subtitle = "Made with Hugo and â¤ï¸"
  dateFormat = "2006-01-02"

  [permalinks]
    blog = "/:year/:month/:day/:title/"

  [params.author]
    name = "Claus Malter" # Your name as shown in the RSS feed metadata
    email = "blog@cmmx.de"
    avatar = "/images/me.jpg"
    bio = 'This blog was created out of pure curiosity. My old Wordpress installation was outdated and so was the content. Since I was interested in Jekyll and Hugo, I started to create this blog based on Hugo and Github Pages. <br /><br />I am a technical consultant specialising in IT infrastructure, backup solutions and software development.'

  [taxonomies]
    category = 'categories'
    tag = 'tags'
    series = 'series' 
  
## Header
[menu]
  [[menu.main]]
        identifier = "home"
        name = "ğŸ Home"
        url = "/"
        weight = 1

  [[menu.main]]
        identifier = "blog"
        name = "ğŸ“°Blog"
        url = "/blog/"
        weight = 2

  [[menu.main]]
        identifier = "categories"
        name = "ğŸ—ƒï¸Categories"
        url = "/categories/"
        weight = 3

  [[menu.main]]
        identifier = "tags"
        name = "ğŸ·ï¸Tags"
        url = "/tags/"
        weight = 4

  [[menu.main]]
        identifier = "aboutme"
        name = "ğŸ™ğŸ»â€â™‚ï¸About Me"
        url = "/aboutme/"
        weight = 5

  ## Footer
  [[menu.footer]]
        name = "Github"
        url = "https://github.com/cloonix"
        weight = 1

    [[menu.footer]]
        name = "Mastodon"
        url = "https://chaos.social/@cloonix/"
        weight = 2

    [[menu.footer]]
        name = "Imprint"
        url = "/imprint"
        weight = 3

    [[menu.footer]]
        name = "Privacy Policy"
        url = "/privacypolicy"
        weight = 4