title = "Claus' Blog"
baseURL = "https://blog.cmmx.de"
timeZone = "Europe/Berlin"
copyright = "Claus Malter"
languageCode = "en-us"

enableEmoji = true
enableRobotsTXT = true
summaryLength = 40

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 2
    ordered = false
  [markup.highlight]
    linenos = true
    lineNumbersInTable = false

[module]
  [[module.imports]]
    path = "github.com/cloonix/smol"

[pagination]
  disableAliases = false
  pagerSize = 3
  path = 'page'

[params]
  description = "Blog based on Hugo SSG and Github pages"
  favicon = "images/favicon.png"
  subtitle = "Made with Hugo and â¤ï¸"
  dateFormat = "2006-01-02"
  mainSections = ['blog' ]

  [permalinks]
    blog = "/:year/:month/:day/:title/"

  [params.author]
    name = "Claus Malter" # Your name as shown in the RSS feed metadata
    email = "blog@cmmx.de"
    avatar = "/images/me.jpg"
    bio = 'This blog was created out of pure curiosity. My old Wordpress installation was outdated and so was the content. Since I was interested in Jekyll and Hugo, I started to create this blog based on Hugo and Github Pages. <br /><br />I am a technical consultant specialising in IT infrastructure, backup solutions and software development.'

  [taxonomies]
    category = 'categories'
    tag = 'tags'
    series = 'series' 
  
## Header
[menu]
  [[menu.main]]
        identifier = "home"
        name = "ğŸ  Home"
        url = "/"
        weight = 10

  [[menu.main]]
        identifier = "blog"
        name = "ğŸ“° Blog"
        url = "/blog/"
        weight = 20

  [[menu.main]]
        identifier = "bookmark"
        name = "ğŸ”— Bookmarks"
        url = "/bookmarks/"
        weight = 25

  [[menu.main]]
        identifier = "categories"
        name = "ğŸ—ƒï¸ Categories"
        url = "/categories/"
        weight = 30

  [[menu.main]]
        identifier = "rss"
        name = "ğŸ“¢ RSS"
        url = "/index.xml#feed"
        weight = 30

 # [[menu.main]]
 #       identifier = "tags"
 #       name = "ğŸ· ï¸Tags"
 #       url = "/tags/"
 #       weight = 40

  [[menu.main]]
        identifier = "aboutme"
        name = "ğŸ™ğŸ»â€â™‚ï¸ About Me"
        url = "/aboutme/"
        weight = 50

  [[menu.main]]
        identifier = "buymeacoffee"
        name = "ğŸº Buy me a beer"
        url = "https://buymeacoffee.com/cloonix"
        weight = 60

  ## Footer
  [[menu.footer]]
        name = "Github"
        url = "https://github.com/cloonix"
        weight = 1

    [[menu.footer]]
        name = "Mastodon"
        url = "https://chaos.social/@cloonix/"
        weight = 2

    [[menu.footer]]
        name = "Imprint"
        url = "/imprint"
        weight = 3

    [[menu.footer]]
        name = "Privacy Policy"
        url = "/privacypolicy"
        weight = 4
